WebApplication2/Areas/Admin/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ProgrammersBlog.Entities.Dtos;
using ProgrammersBlog.Mvc.Areas.Admin.Models;
using ProgrammersBlog.Services.Abstract;
using ProgrammersBlog.Shared.Utilities.Extensions;
using ProgrammersBlog.Shared.Utilities.Results.ComplexType;
using System.Linq;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;

namespace ProgrammersBlog.Mvc.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "admin, editor")]

    public class CategoryController : Controller
    {
        //categorys calling 
        private readonly ICategoryService _categoryService;

        public CategoryController(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }

        public async Task<IActionResult> Index()
        {
            var result = await _categoryService.GetAllByNoneDeletedAsync();

            return View(result.data);


        }
        [HttpGet]
        public IActionResult Add()
        {


            return PartialView("_CategoryAddPartial");


        }
        [HttpGet]
        public async Task<IActionResult> Update(int categoryId)
        {

            var result = await _categoryService.GetCategoryUpdateDtoAsync(categoryId);
            if (result.resultStatus == ResultStatus.Success)
            {
                return PartialView("_CategoryUpdatePartial", result.data);
            }
            return NotFound();

        }
        [HttpPost]
        public async Task<IActionResult> Add(CategoryAddDto categoryAddDto)
        {
            var errors = ModelState.Values.SelectMany(v => v.Errors);

            if (ModelState.IsValid)
            {
                var result = await _categoryService.AddAsync(categoryAddDto, "Aycha Yahia");
                if (result.resultStatus == ResultStatus.Success)
                {
                    var categoryAddAjaxModel = JsonSerializer.Serialize(new CategoryAddAjaxViewModel
                    {
                        categoryDto = result.data,
                        categoryAddPartial = await this.RenderViewToStringAsync("_CategoryAddPartial", categoryAddDto)
                    });
                    return Json(categoryAddAjaxModel);
                }
            }
            var categoryAddAjaxErrorModel = JsonSerializer.Serialize(new CategoryAddAjaxViewModel
            {

                categoryAddPartial = await this.RenderViewToStringAsync("_CategoryAddPartial", categoryAddDto)
            });
            return Json(categoryAddAjaxErrorModel);


        }
        public async Task<JsonResult> GetAllCategories()
        {
            var result = await _categoryService.GetAllByNoneDeletedAsync();
            var categories = JsonSerializer.Serialize(result.data, new JsonSerializerOptions
            {// birbirine referens eden veriler oldugu icin ReferenceHandler kullaniyoruz yoksa sikinti cikabilir
                ReferenceHandler = ReferenceHandler.Preserve


            });
            return Json(categories);
        }
        [HttpPost]
        public async Task<JsonResult> Delete(int categoryToDelete)
        {
            var result = await _categoryService.DeleteAsync(categoryToDelete, "Aycha yahia");
            var deletedCategory = JsonSerializer.Serialize(result.data);
            return Json(deletedCategory);


        }

        [HttpPost]
        public async Task<IActionResult> Update(CategoryUpdatDto categoryUpdatDto)
        {
            var errors = ModelState.Values.SelectMany(v => v.Errors);

            if (ModelState.IsValid)
            {
                var result = await _categoryService.UpdateAsync(categoryUpdatDto, "Aycha Yahia");
                if (result.resultStatus == ResultStatus.Success)
                {
                    var categoryUpdateAjaxModel = JsonSerializer.Serialize(new CategoryUpdateAjaxViewModel
                    {
                        categoryDto = result.data,
                        categoryUpdatePartial = await this.RenderViewToStringAsync("_CategoryUpdatePartial", categoryUpdatDto)
                    });
                    return Json(categoryUpdateAjaxModel);
                }
            }
            var categoryUpdateAjaxErrorModel = JsonSerializer.Serialize(new CategoryAddAjaxViewModel
            {

                categoryAddPartial = await this.RenderViewToStringAsync("_CategoryUpdatePartial", categoryUpdatDto)
            });
            return Json(categoryUpdateAjaxErrorModel);


        }

        /* [HttpPost]
         public async Task<JsonResult> UpdateAsync(int categoryToUpdatId, CategoryAddDto categoryToUpdat)
         {
             var result = await _categoryService.GetCategoryUpdateDtoAsync(categoryToUpdatId);
             if (result.resultStatus == ResultStatus.Success) { 
             result.data.CategoryDto_.Name = categoryToUpdat.Name;
             result.data.CategoryDto_.note = categoryToUpdat.Note;




         }*/
    }


}

WebApplication2/Areas/Admin/Controllers/UserController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProgrammersBlog.Entities.Concrete;
using ProgrammersBlog.Entities.Dtos;
using ProgrammersBlog.Mvc.Areas.Admin.Models;
using ProgrammersBlog.Mvc.Helpers.Abstarct;
using ProgrammersBlog.Shared.Utilities.Extensions;
using ProgrammersBlog.Shared.Utilities.Results.ComplexType;
using System;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;

namespace ProgrammersBlog.Mvc.Areas.Admin.Controllers
{

    [Area("Admin")]// Controllerin Admin icerisinde calisitigini bilmesi icin 

    public class UserController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly IMapper _mapper;
        private readonly SignInManager<User> _signInManager;
        private readonly IImageHelper _imageHelper;

        public UserController(UserManager<User> userManager, IMapper mapper, SignInManager<User> signInManager, IImageHelper imageHelper)
        {
            _userManager = userManager;
            _mapper = mapper;
            _signInManager = signInManager;
            _imageHelper = imageHelper;
        }

        [Authorize(Roles = "admin")]


        public async Task<IActionResult> Index()
        {
            var users = await _userManager.Users.ToListAsync();

            return View(new UserListDto
            {
                Users = users,
                ResultStatus = ResultStatus.Success
            });
        }
        [HttpGet]
        public IActionResult Login()
        {
            return View("UserLogin");
        }
        [HttpPost]
        public async Task<IActionResult> Login(UserLoginDto userLoginDto)
        {
            if (ModelState.IsValid)
            {
                var user = await _userManager.FindByEmailAsync(userLoginDto.Email);
                if (user != null)
                {
                    var result = await _signInManager.PasswordSignInAsync(user, userLoginDto.Password, userLoginDto.RemmberMe, false);
                    if (result.Succeeded)
                    {
                        return RedirectToAction("Index", "Home");
                    }
                    else
                    {
                        ModelState.AddModelError("", "Your email address or password invalid!");
                        return View("UserLogin");

                    }
                }
                else
                {
                    ModelState.AddModelError("", "Your email address or password invalid!");
                    return View("UserLogin");

                }

            }
            else
            {
                return View("UserLogin");

            }
        }
        [Authorize]
        [HttpGet]
        public async Task<ActionResult> Logout()
        {
            await _signInManager.SignOutAsync();
            return RedirectToAction("Index", "Home", "");
        }

        [Authorize(Roles = "admin")]
        [HttpGet]
        public async Task<IActionResult> GetAllUsers()
        {
            var users = await _userManager.Users.ToListAsync();

            var usersListDto = JsonSerializer.Serialize(new UserListDto
            {
                Users = users,
                ResultStatus = ResultStatus.Success

            }, new JsonSerializerOptions
            {
                ReferenceHandler = ReferenceHandler.Preserve
            });
            return Json(usersListDto);


        }
        [Authorize(Roles = "admin")]
        [HttpGet]
        public IActionResult Add()
        {

            return PartialView("_UserAddPartial");
        }
        [Authorize(Roles = "admin")]

        [HttpPost]
        public async Task<IActionResult> Add(UserAddDto userAddDto)
        {
            if (ModelState.IsValid)
            {
                var uploadedImageDtoResult = await _imageHelper.UploadUserImage(userAddDto.UserName, userAddDto.PictureFile);
                userAddDto.Picture = uploadedImageDtoResult.resultStatus == ResultStatus.Success ? uploadedImageDtoResult.data.FullName : "userImages/defaultUser.png";
                var user = _mapper.Map<User>(userAddDto);
                var result = await _userManager.CreateAsync(user, userAddDto.Password);
                // result'tan donen Idenetity objesidir 
                if (result.Succeeded)
                {
                    var userAddAjaxModel = JsonSerializer.Serialize(new UserAddAjaxViewModel
                    {
                        UserDto = new UserDto
                        {
                            ResultStatus = ResultStatus.Success,
                            Massege = $"user with {user.UserName} username has been added successfuly!",
                            User = user
                        },
                        UserAddPartial = await this.RenderViewToStringAsync("_UserAddPartial", userAddDto)
                    });
                    return Json(userAddAjaxModel);

                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError("", error.Description);
                    }
                    var userAddAjaxErrorModel = JsonSerializer.Serialize(new UserAddAjaxViewModel
                    {
                        UserAddDto = userAddDto,
                        UserAddPartial = await this.RenderViewToStringAsync("_UserAddPartial", userAddDto)
                    });
                    return Json(userAddAjaxErrorModel);


                }


            }
            else
            {
                var userAddAjaxModelStateErrorModel = JsonSerializer.Serialize(new UserAddAjaxViewModel
                {
                    UserAddDto = userAddDto,
                    UserAddPartial = await this.RenderViewToStringAsync("_UserAddPartial", userAddDto)
                });
                return Json(userAddAjaxModelStateErrorModel);
            }

        }
        [Authorize(Roles = "admin")]

        public async Task<JsonResult> Delete(int userId)
        {
            Console.WriteLine(userId);

            var user = await _userManager.FindByIdAsync(userId.ToString());
            Console.WriteLine("After user " + user);
            var result = await _userManager.DeleteAsync(user);
            if (result.Succeeded)
            {
                var deletedUser = JsonSerializer.Serialize(new UserDto
                {
                    ResultStatus = ResultStatus.Success,
                    Massege = $"user with {user.UserName} username  has been deleted ",
                    User = user
                }
                    );
                return Json(deletedUser);


            }
            else
            {
                string errorMsgs = string.Empty;
                foreach (var error in result.Errors)
                {
                    errorMsgs = $"{error.Description}\n";
                }
                var deletedUserErorrModel = JsonSerializer.Serialize(new UserDto
                {
                    ResultStatus = ResultStatus.Error,
                    Massege = $"An error ocuured while deleting user with {user.UserName} username\n {errorMsgs}.",
                    User = user
                });
                return Json(deletedUserErorrModel);

            }



        }
        [Authorize(Roles = "admin")]

        [HttpGet]
        public async Task<PartialViewResult> Update(int userId)
        {
            var user = await _userManager.Users.FirstOrDefaultAsync(u => u.Id == userId);
            var userUpdateDto = _mapper.Map<UserUpdateDto>(user);

            return PartialView("_UserUpdatePartial", userUpdateDto);

        }

        [Authorize(Roles = "admin")]

        [HttpPost]
        public async Task<IActionResult> Update(UserUpdateDto userUpdateDto)
        {
            if (ModelState.IsValid)
            {
                bool isNewPictureUploaded = false;
                var oldUser = await _userManager.FindByIdAsync(userUpdateDto.Id.ToString());
                var olduserPicturre = oldUser.picture;
                if (userUpdateDto.PictureFile != null)
                {
                    var uploadedImageDtoResult = await _imageHelper.UploadUserImage(userUpdateDto.UserName, userUpdateDto.PictureFile);
                    userUpdateDto.Picture = uploadedImageDtoResult.resultStatus == ResultStatus.Success ? uploadedImageDtoResult.data.FullName : "userImages/defaultUser.png";
                    if (olduserPicturre != "userImages/defaultUser.png")
                    {
                        isNewPictureUploaded = true;

                    }
                }
                var updatedUser = _mapper.Map<UserUpdateDto, User>(userUpdateDto, oldUser);
                var result = await _userManager.UpdateAsync(updatedUser);
                if (result.Succeeded)
                {
                    if (isNewPictureUploaded)
                    {
                        _imageHelper.DeleteImage(olduserPicturre);
                    }
                    var userUpdateViewModel = JsonSerializer.Serialize(new UserUpdateAjaxViewModel
                    {
                        UserDto = new UserDto
                        {
                            ResultStatus = ResultStatus.Success,
                            Massege = $"user with {updatedUser.UserName} username updated succsefully !",
                            User = updatedUser
                        },
                        UserUpdatePartial = await this.RenderViewToStringAsync("_UserUpdatePartial", userUpdateDto)

                    });
                    return Json(userUpdateViewModel);

                }
                else
                {
                    foreach (var error in result.Errors)

WebApplication2/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ProgrammersBlog.Mvc.Models;
using System.Diagnostics;

namespace ProgrammersBlog.Mvc.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebApplication2/Areas/Admin/Views/Home/Index.cshtml
@model ProgrammersBlog.Mvc.Areas.Admin.Models.DashboardViewModel


@{

    Layout = "_Layout";
    ViewData["Title"] = "Admin Panel";

}




@*<h1 class="mt-4">Dashboard</h1>*@

<ol class="breadcrumb mb-4 mt-2">
    <li class="breadcrumb-item"><a asp-area="Admin" asp-controller="Home" asp-action="Index">Admin</a></li>
    <li class="breadcrumb-item active"><a asp-area="Admin" asp-controller="Home" asp-action="Index">Yönetim Paneli</a></li>
</ol>
<div class="row">
    <div class="col-xl-3 col-md-6">
        <div class="card bg-primary text-white mb-4">
            <div class="card-body">Catogaries (@Model.CategoriesCount)</div>
            <div class="card-footer d-flex align-items-center justify-content-between">
                <a class="small text-white stretched-link" asp-area="Admin" asp-controller="Category" asp-action="Index">Detials</a>
                <div class="small text-white"><i class="fas fa-angle-right"></i></div>
            </div>
        </div>
    </div>
    <div class="col-xl-3 col-md-6">
        <div class="card bg-warning text-white mb-4">
            <div class="card-body">Articles (@Model.ArticlesCount)</div>
            <div class="card-footer d-flex align-items-center justify-content-between">
                <a class="small text-white stretched-link" asp-area="Admin" asp-controller="Article" asp-action="Index">Detials</a>
                <div class="small text-white"><i class="fas fa-angle-right"></i></div>
            </div>
        </div>
    </div>
    <div class="col-xl-3 col-md-6">
        <div class="card bg-success text-white mb-4">
            <div class="card-body">Comments (@Model.CommentsCount)</div>
            <div class="card-footer d-flex align-items-center justify-content-between">
                <a class="small text-white stretched-link" asp-area="Admin" asp-controller="Comment" asp-action="Index">Detials</a>
                <div class="small text-white"><i class="fas fa-angle-right"></i></div>
            </div>
        </div>
    </div>
    <div class="col-xl-3 col-md-6">
        <div class="card bg-danger text-white mb-4">
            <div class="card-body">Users (@Model.UsersCount)</div>
            <div class="card-footer d-flex align-items-center justify-content-between">
                <a class="small text-white stretched-link" asp-area="Admin" asp-controller="User" asp-action="Index">Details</a>
                <div class="small text-white"><i class="fas fa-angle-right"></i></div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-xl-6">
        <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-chart-area mr-1"></i>
                Bar Chart Example
            </div>
            <div class="card-body"><canvas id="myBarChart" width="100%" height="40"></canvas></div>
        </div>
    </div>
    <div class="col-xl-6">
        <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-chart-bar mr-1"></i>


                Bar Chart Example
            </div>

            <div class="card-body"><canvas id="myAreaChart" width="100%" height="40"></canvas></div>

        </div>
    </div>
</div>
<div class="card mb-4">
    <div class="card-header">
        <i class="fas fa-table mr-1"></i>
        Last Posted Articles
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="articlesTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Category</th>
                        <th>Tilte</th>
                        <th>Image</th>
                        <th>Date</th>
                        <th>Views Count</th>
                        <th>Comments Count</th>
                        <th>Active? </th>
                        <th>Deleted? </th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th>#</th>
                        <th>Category</th>
                        <th>Tilte</th>
                        <th>Image</th>
                        <th>Date</th>
                        <th>Views Count</th>
                        <th>Comments Count</th>
                        <th>Active? </th>
                        <th>Deleted? </th>
                    </tr>
                </tfoot>
                <tbody>

                    @foreach (var article in Model.Articles.ArticleListDto_)
                    {
                        <tr>
                            <td>@article.id</td>
                            <td>@article.Category.Name</td>
                            <td>@article.title</td>
                            <td><img src="../../img/@article.thumbnail" class="my-image-table" /></td>
                            <td>@article.Date</td>
                            <td>@article.ViewsCount</td>
                            <td>@article.CommentsCount</td>
                            <td>@(article.isActive? "Yes":"No") </td>
                            <td>@(article.isDeleted? "Yes":"No")</td>
                        </tr>
                    }

                </tbody>
            </table>
        </div>
    </div>

</div>

@Model.
@section Scripts
{
    <script src="~/AdminLTE/js/homeIndex.js" type="application/ecmascript"></script>


    


}